version: '1.0'

stages:
- preparation
- build
- deploy
# - push

steps:

  main_clone:
    title: 'Cloning main repository...'
    type: git-clone
    stage: preparation
    repo: TaeilSeok1/demochat
    revision: ${{CF_BRANCH}}
    git: github
    
  BuildImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: syuo7/demochat
    dockerfile: Dockerfile
    tag: '${{CF_SHORT_REVISION}}'
    
 # PushToDockerHub:
  #  type: push
   # stage: push
    #candidate: '${{BuildImage}}'
    #tag: '${{CF_SHORT_REVISION}}'
    #registry: dockerhub
    #image_name: syuo7/demochat
    
  deploy_to_k8:
    title: deploying to cluster
    type: deploy
    kind: kubernetes
    cluster: ag-idc050
    namespace: default
    service: demochat
    stage: deploy
    candidate:
      image: ${{BuildImage}}
      registry: dockerhub
      
